DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS `CAR` (
`CAR_ID` INTEGER PRIMARY KEY AUTO_INCREMENT,
`PRICE` INTEGER not null,
`YEAR` INTEGER not null,
`MAKE` VARCHAR(100) not null ,
`MODEL` VARCHAR(100) not null,
`AVAILABILITY` BOOLEAN not null,
`ODOMETER` INTEGER not null
);

CREATE TABLE IF NOT EXISTS `CUSTOMER` (
   `CUSTOMER_ID` INTEGER PRIMARY KEY AUTO_INCREMENT,
   `FIRSTNAME` VARCHAR(100) not null,
   `LASTNAME` VARCHAR(100) not null,
   `EMAIL` VARCHAR(100) not null ,
   `PHONE` VARCHAR(100) not null,
);


CREATE TABLE IF NOT EXISTS `BID` (
   `BID_ID` INTEGER PRIMARY KEY AUTO_INCREMENT,
   `CAR_ID` INTEGER not null,
   `CUSTOMER_ID` INTEGER not null,
   `PRICE` INTEGER not null,
   `START_DATE` TIMESTAMP not null,
   `STAT` VARCHAR not null 
);

ALTER TABLE BID ADD CONSTRAINT CUSTOMER_ID FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ;
ALTER TABLE BID ADD CONSTRAINT CAR_ID FOREIGN KEY(CAR_ID) REFERENCES CAR(CAR_ID) ;
